export {
  addVaultCredential,
  createVaultConfigForPassphrase,
  createVaultConfigWithoutSecret,
  decryptVaultJson,
  decryptVaultJsonWithKey,
  deleteVaultCredential,
  encryptVaultJson,
  encryptVaultJsonWithKey,
  getVaultCredentialSummaries,
  getVaultStatus,
  isVaultConfigured,
  isVaultEncryptedPayload,
  isVaultUnlocked,
  lockVault,
  rotateVaultSecret,
  setupVault,
  setupVaultWithoutSecret,
  subscribeVault,
  unlockVault,
  unlockVaultKeyFromConfig,
  unlockVaultKeyFromPasswordlessConfig,
  unlockVaultWithoutSecret,
} from "./vault";
export type {
  VaultConfig,
  VaultCredential,
  VaultCredentialKind,
  VaultCredentialSummary,
  VaultEncryptedPayload,
  VaultStatus,
} from "./vault";
